name: DAST Scan with ZAP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (for building the Docker image)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image locally
      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      # 4. Run Docker container (adjust port as needed)
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 --name my-running-app my-app:latest
          sleep 10  # Give the container some time to start

      # 5. Run ZAP Full Scan on the running web server
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'  # Optional: Include custom rules if you have them
          cmd_options: '-a'  # Active scan mode (default)

      # Optional: Stop the container after scan
      - name: Stop Docker container
        if: always()
        run: |
          docker stop my-running-app
          docker rm my-running-app
